### ISSUE TITLE
Error in WRI code

### ISSUE THREAD

**Issue by matthieubulte** [Chao0209/Density-Review#1]
Hi there,

I was trying to reproduce some of your results and you seem to be missing the definition of `m` in the following code, leading to an error (`Error in CVXR::Variable(m) : object 'm' not found`) being raised whenever quadratic programming has to be used in the Fréchet regression.

https://github.com/czhang-pstat/Density-Review/blob/main/Others/WRI-master/R/quadrcticQ.R#L18

The fix I found is simply to add `m = length(t)` at the beginning of the function.

**Comment by czhang-pstat** [comment]
Hi Matthieu, thanks a lot for the feedback (and my sincere apologies for this late reply, I was getting started for my new job and got behind on keeping up).  Indeed, we have published the package [WRI](https://cran.r-project.org/package=WRI), and the issue you pointed out was fixed by `m = length(Qmat[i, ])`.  Again, thanks for pointing out the issue!
